// <auto-generated />
using System;
using DataAccess.Context.IdentityContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccess.Context.IdentityContext.Migrations
{
    [DbContext(typeof(AppIdentityDbContext))]
    [Migration("20241026113533_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApplicationCore.UserEntites.Concrete.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5ba59a20-2057-4a8a-a417-80c119f79971"),
                            CreatedDate = new DateTime(2024, 10, 26, 11, 35, 33, 50, DateTimeKind.Utc).AddTicks(6789),
                            Name = "admin",
                            NormalizedName = "ADMIN",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("bf6a5a19-2bc4-4e47-af9a-c52f4936cc4c"),
                            CreatedDate = new DateTime(2024, 10, 26, 11, 35, 33, 50, DateTimeKind.Utc).AddTicks(6844),
                            Name = "customerManager",
                            NormalizedName = "CUSTOMERMANAGER",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("87fb18de-280e-48bc-abc7-80eef7448fe4"),
                            CreatedDate = new DateTime(2024, 10, 26, 11, 35, 33, 50, DateTimeKind.Utc).AddTicks(6847),
                            Name = "teacher",
                            NormalizedName = "TEACHER",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("754ee8ce-7cd4-4ebb-989f-36d3de20772e"),
                            CreatedDate = new DateTime(2024, 10, 26, 11, 35, 33, 50, DateTimeKind.Utc).AddTicks(6982),
                            Name = "student",
                            NormalizedName = "STUDENT",
                            Status = 1
                        });
                });

            modelBuilder.Entity("ApplicationCore.UserEntites.Concrete.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5db9b8aa-54c3-4b7a-a102-b21207d6646c"),
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "519eee9e-031c-40b1-837e-34d2175b73dc",
                            CreatedDate = new DateTime(2024, 10, 26, 11, 35, 32, 424, DateTimeKind.Utc).AddTicks(2767),
                            Email = "admin@bilgeadam.com",
                            EmailConfirmed = false,
                            FirstName = "Administrator",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@BILGEADAM.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAELhsBwaqb0f7BMrivtsRMISrXZzTOB1Ptc0I4OARptswCwF047bk3pQfTqAE4HnYoA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8a6b2739-2c2c-4825-b542-409e56e4a0d4",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = new Guid("79c7f482-f112-4024-aa6c-05df190ce3ff"),
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(1994, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "9194edef-a34b-4cc9-84e4-3cdd4d212daf",
                            CreatedDate = new DateTime(2024, 10, 26, 11, 35, 32, 561, DateTimeKind.Utc).AddTicks(4681),
                            Email = "pelin.ozerserdar@bilgeadam.com",
                            EmailConfirmed = false,
                            FirstName = "Pelin",
                            LastName = "Özer Serdar",
                            LockoutEnabled = false,
                            NormalizedEmail = "PELIN.OZERSERDAR@BILGEADAM.COM",
                            NormalizedUserName = "PELIN.OZERSERDAR",
                            PasswordHash = "AQAAAAIAAYagAAAAEAiIEX1sBtunFKPlR2DNVGyl6WygLIH+4peOqXDnK5+Ap1/BRjNCHGoKnF/u1hfFlw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5f856662-06e6-4051-a91e-0ef0702e7d0d",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UserName = "pelin.ozerserdar"
                        },
                        new
                        {
                            Id = new Guid("f2d17592-2c75-4a38-a8db-07e13fc4778f"),
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(1996, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "931348e7-be49-46b4-ad3c-0df33217011f",
                            CreatedDate = new DateTime(2024, 10, 26, 11, 35, 32, 683, DateTimeKind.Utc).AddTicks(5466),
                            Email = "sinaemre.bekar@bilgeadam.com",
                            EmailConfirmed = false,
                            FirstName = "Sina Emre",
                            LastName = "Bekar",
                            LockoutEnabled = false,
                            NormalizedEmail = "SINAEMRE.BEKAR@BILGEADAM.COM",
                            NormalizedUserName = "SINAEMRE.BEKAR",
                            PasswordHash = "AQAAAAIAAYagAAAAENh+Ke5nb7WasY/6aj4YwYY1l1ZwtQpHEDyLQkmRVeV3syuKypUGi8YSyNm7JEYyNA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9456b472-f5ef-4616-b315-36e14e0754e9",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UserName = "sinaemre.bekar"
                        },
                        new
                        {
                            Id = new Guid("389a9486-374b-4a4b-85ef-b2faed25f907"),
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(1996, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "e70263d6-184b-48cf-bc6e-1acde4075eb0",
                            CreatedDate = new DateTime(2024, 10, 26, 11, 35, 32, 806, DateTimeKind.Utc).AddTicks(7580),
                            Email = "perin.aycilsahin@bilgeadam.com",
                            EmailConfirmed = false,
                            FirstName = "Perin",
                            LastName = "Aycil Şahin",
                            LockoutEnabled = false,
                            NormalizedEmail = "PERIN.AYCILSAHIN@BILGEADAM.COM",
                            NormalizedUserName = "PERIN.AYCILSAHIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEIXgJkRgocaXwHOhXI4LgisFxgrFB7wOQQlzjLKf2cNjATi1EhcYycYkVbAc8fZ0CA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "52cda167-517c-4b86-8a39-7dbc9274c352",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UserName = "perin.aycilsahin"
                        },
                        new
                        {
                            Id = new Guid("ca21aa0d-b8b7-433c-89f6-bc2480a694d1"),
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(1985, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "13d442d3-0e18-46f9-a3bb-4c65d182748e",
                            CreatedDate = new DateTime(2024, 10, 26, 11, 35, 32, 928, DateTimeKind.Utc).AddTicks(6896),
                            Email = "ahmet.cekic@bilgeadam.com",
                            EmailConfirmed = false,
                            FirstName = "Ahmet",
                            LastName = "Çekiç",
                            LockoutEnabled = false,
                            NormalizedEmail = "AHMET.CEKIC@BILGEADAM.COM",
                            NormalizedUserName = "AHMET.CEKIC",
                            PasswordHash = "AQAAAAIAAYagAAAAEOojawf57ilUpHBhG0gjtOQPtCkgg0X0E6WvOlXve3+IY4oD5J8k/bkdhNtZijQf5Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7178b4b9-910a-4740-9b65-7c8404c832cf",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UserName = "ahmet.cekic"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("5db9b8aa-54c3-4b7a-a102-b21207d6646c"),
                            RoleId = new Guid("5ba59a20-2057-4a8a-a417-80c119f79971")
                        },
                        new
                        {
                            UserId = new Guid("79c7f482-f112-4024-aa6c-05df190ce3ff"),
                            RoleId = new Guid("bf6a5a19-2bc4-4e47-af9a-c52f4936cc4c")
                        },
                        new
                        {
                            UserId = new Guid("f2d17592-2c75-4a38-a8db-07e13fc4778f"),
                            RoleId = new Guid("87fb18de-280e-48bc-abc7-80eef7448fe4")
                        },
                        new
                        {
                            UserId = new Guid("389a9486-374b-4a4b-85ef-b2faed25f907"),
                            RoleId = new Guid("754ee8ce-7cd4-4ebb-989f-36d3de20772e")
                        },
                        new
                        {
                            UserId = new Guid("ca21aa0d-b8b7-433c-89f6-bc2480a694d1"),
                            RoleId = new Guid("754ee8ce-7cd4-4ebb-989f-36d3de20772e")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("ApplicationCore.UserEntites.Concrete.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ApplicationCore.UserEntites.Concrete.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ApplicationCore.UserEntites.Concrete.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("ApplicationCore.UserEntites.Concrete.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationCore.UserEntites.Concrete.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ApplicationCore.UserEntites.Concrete.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
